"""empty message

Revision ID: 6c167b3fff89
Revises: 779321d77b33
Create Date: 2026-09-22 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c167b3fff89'
down_revision = '779321d77b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('builtin_app_id', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'builtin_app_id')
    # ### end Alembic commands ###
