"""empty message

Revision ID: 703448ce6797
Revises: ae76d47b437e
Create Date: 2026-09-21 10:08:07.342438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703448ce6797'
down_revision = 'ae76d47b437e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_agent_conversation_id', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('assistant_agent_conversation_id')

    # ### end Alembic commands ###
