"""empty message

Revision ID: 93075ff88f09
Revises: 23521203c2f5
Create Date: 2026-08-08 19:21:34.860128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93075ff88f09'
down_revision = '23521203c2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
